### ISSUE TITLE
Do not sync default values to server (to reduce api call size)

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#106]
The way [default values work has been updated](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#default-values).

I will add the functionality to not to sync these default values to the server **if they are equal to the default value itself**. As soon as any of these values is modified (and not equal to the default value anymore) it will be synced to the server.

This enables our API calls to be as light as possible and allow us to not save any redundant data on the server. Only in cases where you would also need these default values on the server side, you could disable this ability.

---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>

**Comment by louisameline** [comment]
Duplicate of https://github.com/mesqueeb/vuex-easy-firestore/issues/241

**Comment by louisameline** [comment]
I'll reopen this issue, it wasn't a duplicate actually

**Comment by louisameline** [comment]
Hi! This seems like a very minor optimization, how much money will it save? Remember that 1Go bandwidth = 0.20$ approximately.
On the other hand, it can be annoying not to have the default values in a document, because:
- it assumes that all parties which will handle the data will know the default values
- the default values may change tomorrow, but maybe I'd like old documents to keep their old value
So overall, I wouldn't encourage this and I would close the issue. Thank you

**Comment by mesqueeb** [comment]
I see your points and find them valid. 😄
