### ISSUE TITLE
Closing channel with clearModule:true destroys reactivity

### ISSUE THREAD

**Issue by usu** [mesqueeb/vuex-easy-firestore#112]
Module defined like this:
```
const exampleModule = {
  firestorePath: 'examples',
  firestoreRefType: 'collection',
  moduleName: 'examples',
  statePropName: 'docs',
};
```

In Vue component:
```
  data() {
    return {
      examples: this.$store.get('examples.docs'),
    };
  },
```

When I close the channel with clearModule=true and then reopen the channel, reactivity in the component is lost. It works fine if reactivity is defined one level up.
```
 data() {
    return {
      exampleStore: this.$store.get('goals'),
    };
  },
  computed: {
    examples(){
      return this.exampleStore.docs;
    },
  },
```

I believe this can be improved by not throwing the docs object away, but removing only its content during RESET_VUEX_EASY_FIRESTORE_STATE.
https://github.com/mesqueeb/vuex-easy-firestore/blob/9dae28c4f717283ab447d3e6e4452d983531793a/src/module/mutations.ts#L54

**Comment by mesqueeb** [comment]
@usu 
Thanks very much for this issue.

As you said, I can fix this for your use case by changing that line:
```js
return self._vm.$set(state, state._conf.statePropName, {}) 
```
to
```js
return Object.keys(state._conf.statePropName).forEach(key => {
  self._vm.$delete(state._conf.statePropName)
})
```

I will consider doing this. However, I also think in your case it's not a good design to work with the vue component's data.

A Vue component's data is in most cases supposed to be assigned once, until the component is destroyed. Then if the component is rendered again the data is assigned again.

That's why if you want the component to use data from vuex, in your case I would only use computed properties instead. Logic wise this is a better design in my opinion.

In your case I would just do:

```js
computed: {
  examples () {
    return this.$store.state.examples.docs
  }
}
```
I think this will stay reactive even with the current implementation of `RESET_VUEX_EASY_FIRESTORE_STATE`.

If you have any opinion on why you'd want to do it with the `data () {}` prop of a vue component, I'd love to know why!

PS, what I also often do is in every component I'd add:
```js
computed: {
  state () { return this.$store.state },
  getters () { return this.$store.getters },
}
```
Then I have more easy access to the state and getters of the store in my components.

**Comment by mesqueeb** [comment]
@usu i have updated the library.
Should be fixed in latest version.

Please try `npm i vuex-easy-firestore@latest`
and let me know!

If it is fixed, please close the issue! ♡

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by usu** [comment]
Tested with 1.25.1, works like a charm 🤩

And thanks for sharing your thoughts above. It is always good to learn.
