### ISSUE TITLE
[Question] Vuex ORM

### ISSUE THREAD

**Issue by CelticParser** [mesqueeb/vuex-easy-firestore#137]
Does Vuex Easy Firestore play nicely with Vuex ORM? If the two can be utilized, what is your recommended config>

Cheers!

**Comment by mesqueeb** [comment]
@CelticParser Never tried this before. Let me know if you do!

My reasoning. Vuex-ORM (the author is actually a friend of mine : P) is more of a solution to easily connect a traditional database with Object-Relational Mapping with Vuex. I would argue that this is very powerful for MySQL or Postgre databases, and a perfect fit for when you are using a back-end like Laravel, hosting your own database.

When you use the NoSQL Firestore database, the whole way of thinking is different. Please check out [this video from the Firebase team](https://youtu.be/v_hR4K4auoQ) about NoSQL databases.

If you have some experience with Firestore already you will understand it's often more economical to save more duplicate data in a lot of places instead of linking things with document ID's.

Eg.
- Saving just a user id to a post and getting that post as well as the user record to get the username is more the traditional SQL way. For these things Vuex ORM works really well.
- Saving both the user id and username and anything else you'd wanna show together with posts, directly onto that post record is more of the NoSQL method.

This is why I believe in 99% of the cases, you'll have enough with just using Vuex-easy-firestore.

Please do however tell me more about how you think to be able to use both vuex-easy-firestore and vuex-orm would be beneficial for your app, and tell me exactly the kind of things you wish you'd be able to do. Maybe I can give some advise or I'll agree to some points and give vuex-easy-firestore extra functionality!

**Comment by mesqueeb** [comment]
Going to close for maintenance purposes. But feel free to continue the discussion below! 🙃
