### ISSUE TITLE
Suggestion: play nicely with browser state persistence

### ISSUE THREAD

**Issue by bpkennedy** [mesqueeb/vuex-easy-firestore#138]
Not a high priority or anything, but I tried setting up Vuex-Persist for some localStorage persistence across browser reloads, and had some issues with circular references in json.  However, I wasn't sure if it was my configuration or this library's manner of implementation.

Either way, it would be nice to have that built into the configuration as an option.  Vuex-Persist is one - there's another couple libraries.  I have no preference whether it's a library or something you roll yourself - just the localStorage persistence would be nice (maybe option for sessionStorage and/or IndexDB)?

**Comment by mesqueeb** [comment]
As far as I know [offline persistence](https://firebase.google.com/docs/firestore/manage-data/enable-offline) offered by the Firebase JS SDK works fine. Please try integrating that!
```
Firestore (Google Servers)
⇅  
Firebase JS SDK (Client side)
⇅
vuex-easy-firestore
⇅
Vuex
```
From looking at the flow of data above, in my opinion it's probably smarter to get offline persistence to work in the Firebase JS SDK layer. They are closest to the actual Database and even keep track of data that needs to be pushed to the server when your device comes back online.

You should avoid "vuex-persist" in my opinion because it's a much simpler integration and a more general library for when you have data already in vuex. You'll probably have a very hard time getting that to work with the firebase JS SDK with or without my library in between.  : D

I'll close this issue but feel free to continue the discussion!
