### ISSUE TITLE
Customize time between firestore calls

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#146]
How can you customize the time between calls? 

I'd like to send some events instantly.

**Comment by mesqueeb** [comment]
Ok this is not yet customizable but can easily be made so. I could push an update for this within a couple of hours, but before I start i'd first like to hear about your use case. This way I can decide if it's common enough to put in my library or just teach you a different way you could do that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thokkane** [comment]
The use case here is that sometimes the next call can be made only after previous call has completed. For example if the id of a newly created doc is needed, we need to first get the new id and then make the next call.

Another use case is in collaborative environments the time between text edits needs to be faster so in these cases it would be nice to be able to set in the call if it should go into batching or sent of immediately.

**Comment by mesqueeb** [comment]
@thokkane 

## Set a shorter sync debounce

You can now set a [custom sync debounce duration](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#custom-sync-debounce-duration).

Please update to the latest version. (> 1.29.0)

## Retrieve document id after insert

Please also note that you _do not need_ a shorter debounce duration _just_ to get the document ID.
Please see **Manually assigning doc IDs** in the ['collection' mode documentation](https://mesqueeb.github.io/vuex-easy-firestore/add-and-manage-data.html#collection-mode).

There you can see that when you make an insert you **can retrieve the new ID immediately**.

> Every insert will automatically generate an ID and return a promise resolving in the ID of the doc added to the store and Firestore.
> This is how you can use the auto-generated ID:
```js
const id = await dispatch('moduleName/insert', newDoc) // returns id
// mind the await!
// or
dispatch('moduleName/insert', newDoc)
  .then(id => { /* do something with the new id */ })
```

## No sync debounce on specific calls

If for any reason you need to invoke the sync to ignore the debounce and immediately need to invoke your patch or insert to be synced to the server you can just dispatch this after your patch or insert action:
```js
dispatch('moduleName/insert', newDoc) // or patch or set
dispatch('moduleName/batchSync')
```
You'll have to do some testing on your end however. If this doesn't work (because the docs need to be prepared _before_ the batchSync, and I'm not sure that'll finish when immediately firing these two after each other) maybe you'll have to do this:
```js
dispatch('moduleName/insert', newDoc) // or patch or set
setTimeout(_ => dispatch('moduleName/batchSync'), 1)
```

Please let me know if the above 3 solutions I gave you work and if they do close this issue!

<sub>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
I'm going to close this since it's already implemented as requested.
Feel free to continue the discussion below.

**Comment by thokkane** [comment]
@mesqueeb sorry for long response time. Just tested the last option and its working as intended.
