### ISSUE TITLE
Sample app reference in documentation help

### ISSUE THREAD

**Issue by bpkennedy** [mesqueeb/vuex-easy-firestore#151]
Hi @mesqueeb , I'm a couple weeks away from a first release of a Vuex-easy-firestore app.  I was wondering if you'd be interested in referencing projects that have used the library - it may also serve a dual purpose of a functional crud example (if my implementation meets your expectations).  I am keeping my source public.

I would also be happy to change code to better exemplify implementation if you find things that could be better/clearer.

Let me know: 
https://gitlab.com/bpkennedy/kenshi-journal

**Comment by mesqueeb** [comment]
I’ll look into your code!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Update to latest firebase and delete custom timestamp settings, as firebase will guide you regarding this in the console log: 
https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/firebase.js 

You're using `let app` but not reassigning that variable anywhere here:
https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/main.js
Shouldn’t you `app = new Vue` inside the auth listener?

You’re not opening db channel for entries? Or where do you do this?

Currently when using arrayUnion or remove on a value that is not an array, it will throw an uncaught error. Are you sure the value expected here is always an array?
https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/store/modules/entries.js#L34

Hooks dont need to be added when not used. So you can delete all hook functions from here
https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/store/modules/entries.js#L115
Same for these hooks:
https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/store/modules/profiles.js#L62

Don’t know how you feel about it but you can change this:
```js
 setEntry (state, entry) {
    Vue.set(state, 'entry', Object.assign({}, entry))
  },
```
To this:
```js
 setEntry (state, entry) {
    this._vm.$set(state, 'entry', Object.assign({}, entry))
  },
```
Then you can remove the need to import vue at the top of the file. 😉

I prefer `{ dispatch }` over `store` as first param in actions like:
`async likeStory (store, { storyId, like }) { `

It’s weird what you do here:
```js
async likeStory (store, { storyId, like }) { // eslint-disable-line camelcase
    await store.dispatch('publicStoriesData/patch', {
      id: storyId,
      likes: arrayUnion(like)
    }, { root: true })
  },
```
Change to:
```js
async likeStory (store, { storyId, like }) { // eslint-disable-line camelcase
    await store.dispatch('patch', {
      id: storyId,
      likes: arrayUnion(like)
    })
  },
```

And finally, in all actions related to my library, since vuex is not yet natively TypeScript compatible, don’t you need manual param checks when an action is dispatched with an undefined value? Firestore can’t sync an undefined value and will throw an error, which might cause your ui to freeze for the end user. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bpkennedy** [comment]
1. firebase updated and timestamps no longer need to be set - fixed.

2. assigned app to `app` variable - yes, I should have been doing that.

3. For openChannel of Entries - I couldn’t think of a great way to accomplish this.  I needed to be connected to the entries collection, but not get ALL the entries (openChannel).  So, I’m not doing openDbChannel and just making one-off calls instead for what I need.  I also needed the query to be dynamic (get all where storyId is xxxx) and that query is going to change depending on the story, so I couldn’t put that directly in the config for that module.  Is there a better way?

4. Entries using arrayUnion - I believe so.  Entries in the database is an array type, so it’ll only take that.  Haven’t seen thrown errors on save for that so far, in the ui.

5. redundant client/server hooks have been removed.

6. swapped `Vue.set` for `this._vm.$set` for brevity.  Wasn't so concerned about importing Vue, as I thought that import did imports "smartly" i.e. would not actually import a second time if it was already loaded, but it's there now for clarity sake.

7. Now using destructuring of the action params for brevity (`store` becomes `{ dispatch, commit, state }` or whatever minimal needed.

8. When calling a local module action (like in stories modules can calling `.dispatch('storiesModules/thing')`) I have changed to calling `.dispatch('thing')` and removed the `root: true`.  However in situations where I need to call a different module action I will need to keep the verbose so that it knows how to get there (unless I am incorrect?).

Thanks for looking it over sir!

**Comment by mesqueeb** [comment]
3 I think you're correct. I can't think of a better way either 

8 exactly. 

4: do you have default values? Please point me to the file where you make a new entry. I wanna see two you do it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bpkennedy** [comment]
4. Sure, when I create a new story I do include a default empty array for the `entries` property.  https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/store/modules/stories.js#L80

This makes that property an Array type in firestore.  And then later when I am adding/removing an entry from the entries collection I use only arrayUnion and arrayRemove to change that field (https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/store/modules/entries.js#L33).

Is that what you were looking for?

**Comment by mesqueeb** [comment]
I guess my final piece of advice is the values you are adding to an [initial story insertion here](https://gitlab.com/bpkennedy/kenshi-journal/blob/master/src/store/modules/stories.js#L80). Should also best be added to [defaultValues](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#default-values) to prevent any issues when a doc retrieved from the server doesn't have those props.

It might be fine now, but once people use your DB and you add eg. a new field with an array, not all docs will have that prop, even though your app might expect an array. That's why it's best to always add default values to the settings of my library.

**Comment by mesqueeb** [comment]
Let me know if this helped you. Feel free to continue the discussion below!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by bpkennedy** [comment]
As I thought through the implications of setting the default values in the vuex-easy-module startup I think that would be a pretty good way to handle net new future properties.  I'm going to update my implementation of the default values using the module config as well.  Will post back here when complete.
