### ISSUE TITLE
Create document with custom id

### ISSUE THREAD

**Issue by razbakov** [mesqueeb/vuex-easy-firestore#154]
Please provide an action to be able to do the following operation:

```js
await firestore.collection(firestorePath).doc(id).set(data)
```

In my project I have to ensure of data consistency between different storages and the best way to do it is to get id from remote database and use it as an id in firestore collection.

**Comment by mesqueeb** [comment]
You can pass a custom ID when inserting or patching. 
See the [documentation](https://mesqueeb.github.io/vuex-easy-firestore/add-and-manage-data.html#collection-mode) where it says **manually assign doc id's**

Is this what you are looking for? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CelticParser** [comment]
I use firebases' callback the following way to set the user's firestore account id to match that of the `authResult.user.uid`:

```js
callbacks: {
    signInSuccessWithAuthResult: function(authResult) {
      const newUser   = authResult.user
      const userItems = {
        avatar  : newUser.photoURL,
        eMail   : newUser.email,
        userName: newUser.displayName,
        userUid : newUser.uid,
      }

      usersCollection.doc(account.userUid).set(userItems)

      // === None of these work === //
      // const id = userItems.newUser.uid
      // Store.dispatch('addUser/set', userItems.userUID)
      // Store.dispatch('addUser/setUserId', id)
      // Store.dispatch('addUser/set', userItems) // <- This will set data but not the UID for the doc id

      return false;
    },
  },
```
However, I can't figure out how to replicate this using `vuex-easy-firestore`

```js
// addUser.js module
export default {
  firestorePath: 'users',
  firestoreRefType: 'collection',
  moduleName: 'addUser',
  statePropName: 'data',
}
// Also tried
export default {
  firestorePath: 'users/{userID}',
  firestoreRefType: 'doc',
  moduleName: 'addUser',
  statePropName: 'data',
}

Anything that I get out of the docs doesnt set the document id with the custom id needed. Appreciate your help with this.  Thnx!

**Comment by mesqueeb** [comment]
You'ru doing some things wrong and I think I can help you. But do you want to use a doc or collection for 'addUser' module? 

Also addUser is a weird name for a module, why not just use a module called 'user'? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CelticParser** [comment]
Actually we're using 'registerUser'. It's only used at registration. When there are hundreds of modules being utilized, implementing "source of truth" to prevent "mental mapping" becomes a necessity.

We started playing around with this plugin last week (again) in thought that it would reduce broilerplate - and it does! However it was noticed over the weekend while inspecting what it does via the Vuex Dev Tool, it was discovered vuex-easy-firestore adds a ton of un-necessary bloat on the client side.  This plugin is great for small apps and quick prototyping but not for enterprise or government apps - esp. when local store is limited by the browser and not everything can be lazyloaded.  

Thanks and we appreciate your efforts.

**Comment by razbakov** [comment]
@mesqueeb Thank you, it looks promising. I gonna check it.

So for example above from @CelticParser the code should be:

```
userItems.id = userItems.userUID
Store.dispatch('addUser/insert', userItems)
```

P.S. Better use `moduleName: 'users'`

**Comment by CelticParser** [comment]
@razbakov Thnx for the input. However that does not truly create a doc/collection with a custom id. Test by looking at the id within the FireStore db. Next log out or, switch machines/devices, or delete the cache; Then log back in and inspect the db; you will discover that the plugin will create a second entry with a new id. I walked in this morning with 3 devs saying, "Nope, I wouldn't use it (the plugin)".

Mostly too because the plug-in creates 17 stores on the client side (needing tem or not) - This was tested to show it adds 2.7kb of unneeded bytes across the wire and onto the user's' machine - And multiply that for EVERY module that the app calls on vuex-easy-firestore. Sometimes its better not to use the shortcut and spend the extra few minute typing. Look for yourself. This plugin a great idea and there was a lot of work put into it - It just won't for our use.

I wanted to send this privately so my apologies to you ( only to help out - nothing more so I hope it is ).  One of my contractors wrote a nice 'up-to-date' article on Medium titled: [Effectively Naming Software Thingies](https://medium.com/@rabinovichsagi/effectively-naming-software-thingies-fcea9d78a699).

TL;TR:

As a rule of thumb, objects are named with nouns. i.e: a db object or .json object, or even a link would be named with a noun.  In this case `user` would work great for `firestorePath: 'some_noun>'` because it is describing a object. Now with `methods`, they are named with a verb because it is a action. Modules do something in every form (the code is doing something). This means that `moduleName: '<some-verb-name>'` should be a verb to describe what it does because in interacts with an object. This is the best practice used on large teams. With that in mind, `moduleName: 'insertUser | registerUser | addUser'` would make for proper nomenclature (matching the file.js name too).  Imagine you were just onboarded and you are going thru the code to familiarize yourself and you see a method/module accessed with `user`?? I would be thinking, "User what? What does this do? Crap, now I have to spend time digging for what it does".  The only time to use a noun to name a module (like in vuex) is for "dumb-modules".

**Comment by mesqueeb** [comment]
@CelticParser razbakov is correct as that would be the way to do it. The problem you are having now is clearly something you are doing wrong in your setup. If you provide me with more of your code I can help you find the problem. 
  
Btw, I'm not sure about your counter arguments... this plugin definitely does not add 17 stores!! 😃 as I said: I think you might be using it wrongly. 

The only thing Vuex easy Firestore does is take a module that's passed to it, add boilerplate actions, mutations, getters and state and then register that module to the store. 

Please look through the source code and make sure you understand everything before deciding to use it is a production app. 

Either way I feel that if you are going to write your own boilerplate actions that sync stuff to Firestore, you'd eventually come up with a rather similar module. Of course you can save a few bytes here and there when you wrote everything yourself, because you'd only add the functionality you'd really need. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
