### ISSUE TITLE
Update value in firestore array field

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#163]
I have an array in firestore as a field in a document. I need to update one value in a specific item in the array. How can a specific array item be updated? Below is an example.

```javascript


texts: [
        {
          text: 'test1',
          x: 10,
          y: 10,
          fontSize: 16,
        },
        {
          text: 'test2',
          x: 10,
          y: 10,
          fontSize: 16,
        }
      ]


this.$store.dispatch('docs/set', {
            id:this.itemId,
            texts[0]: {
              [field]: "new text"
            }
        })
```

**Comment by mesqueeb** [comment]
@thokkane 
This is not possible because of limitations of the firebase firestore SDK. The only way to do this would be by replacing the whole array.

In your example:
```js
const newArray = texts
newArray[0].text = 'new text'
this.$store.dispatch('docs/set', {
  id: this.itemId,
  texts: newArray
})
```

But it's much better to avoid working with arrays and only work with objects in my opinion.

See this blog post of firebase: [Best Practices: Arrays in Firebase](https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html)

I'll close this issue, but feel free to continue the conversation!
<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by thokkane** [comment]
@mesqueeb thank you.

**Comment by codegrue** [comment]
How do you manage a sub-collection within a document? It looks like this is possible with pure Firestore syntax:

https://stackoverflow.com/questions/48873465/how-to-add-sub-collection-to-a-document-in-firestore

Is there an equivalent syntax for VuexEasyFirestore?

**Comment by mesqueeb** [comment]
Codegrue. Please don’t comment an unrelated question in a closed thread. 🙃 it’s always better to open a mew issue. 

As for your question: it’s unclear what your question is? There’s no concept of “adding sub collections” in Firestore to begin with. There’s only the concept of adding adding docs at certain paths. If a doc is added in a path where there’s no collection yet, a collection will automatically be created. 

VEF is the concept of having one vuex module per path. The “set” or “insert” action you can use will automatically use that path you define in your config. If you want to add a doc in a “subcollection” you just need to create a new VEF module with the specific path of that submodule. 

Do you understand?😉

Btw also note you can use path variables to keep the possibility to change your firestorepath during runtime. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@codegrue 
Also please note that you can still use the Firebase JS SDK for Firestore to do anything you want. Vuex-easy-firestore doesn't limit this at all, it just gives you some pre-made actions and a handy way to organise your data in modules.

**I'll give you an example:**
eg.
```js
{
  firestorePath: 'countries/belgium/cities',
  firestoreRefType: 'collection',
  moduleName: 'cities',
  statePropName: 'data',
}
```
If you have a VEF module like above, you can still (like the examples in the SO answer) do this:
```js
db.collection('countries/belgium/cities').add({name: 'Antwerp'})
// or
db.collection('countries/belgium/cities').doc('antwerp').set({name: 'Antwerp'})
```

VEF is even handier, because it will save `db.collection('countries/belgium/cities')` inside a getter for you.
(When you have a look at the actions and getters that are added to a VEF module you can find a getter called `dbRef`, which is purely the Firestore reference object with the `firestorePath` you have defined.)

So in this example with VEF you can do this as well:
```js
store.getters['cities/dbRef'].add({name: 'Antwerp'})
// or
store.getters['cities/dbRef'].doc('antwerp').set({name: 'Antwerp'})
```

As you can see, there are no limitations, just ways to make your life easier.

If in your case you want to add a document to a sub-collection (one you do not have a module set up for) you can do this:
```js
db.collection('countries/belgium/cities/antwerp/street').add({name: 'Kerkstraat'})
// or
db.collection('countries/belgium/cities/antwerp/street').doc('kerkstraat').set({name: 'Kerkstraat'})
// or
store.getters['cities/dbRef'].collection('antwerp/street').add({name: 'Kerkstraat'})
// or
store.getters['cities/dbRef'].collection('antwerp/street').doc('kerkstraat').set({name: 'Kerkstraat'})
```

And again, you see, there are 0 limitations.

**Comment by codegrue** [comment]
Thank you. These examples are very helpful. Might be a good addition to the docs since I don't think I would have ever known about 'dbRef' without this converastion.

**Comment by lylest** [comment]
` firestore().collection("simple_poll").where("id","==",id).get().then(snapshot => {`
                               ` snapshot.forEach(doc=>{`
                                  `const modify =  doc.data().poll_options.map(option =>` 
                                      `option.id === option_id ? {...option,votes:option.votes + 1} : option)`
                                      `doc.ref.update({`
                                          `poll_options:modify`
                                      `})`
                               ` })`
                             `})`
