### ISSUE TITLE
modules inside modules (dynamic module registration)

### ISSUE THREAD

**Issue by ctwhome** [mesqueeb/vuex-easy-firestore#165]
Hallo @mesqueeb, I am trying to find the solution for a "basic" problem, but I can't find it anywhere.

I am struggling on how to distribute the data of the data model in the correct way. I am building an app to manages ideas within different organizations. _Organizations_ have _Ideas_ and Ideas have _Comments_. 

First thing I thought was to create 3 main collections, one for organizations, other for ideas and another for comments. So I can filter organizations by user ID, and ideas by OrganizationsID...and so on. 

My ideas vuex module looks like this: 
```js
export default {
  firestorePath: 'organizations/{organizationId}/ideas',
  firestoreRefType: 'collection', // or 'doc'
  moduleName: 'ideas',
  statePropName: 'data',
}
```

The problem I have is that when I retrieve the ideas for an organization, the 'ideas' module in Vuex saves those filtered ideas.. but when I move to another organization (different route page), the same ideas module is used to store the ideas of this new organization. 

this makes sense to me so I thought that moving the ideas collection to a sub-collection of _Organizations_ would stores the subcollection as a child of Organizations module. But nom in vuex I still get only one module: ideas, and there is no way (that I found) to store that subcollection inside the vuex module "organizations". Doing something like this didn't do the trick 😅:
```js
export default {
  firestorePath: 'organizations/{organizationId}/ideas',
  firestoreRefType: 'collection', // or 'doc'
 **moduleName:'organizations/{organizationId}/ideas',**
 statePropName: 'data',
}
```

_Why do I want to have sub-collections ideas inside the Vuex module of organizations?_
Because then I don't have to read again all the ideas from a different organization when I am jumping from one to another?

Do you have any advice on how to do this, is there something in vuex-easy-firestore that moves subcollections inside a different module? 

I hope this makes any sense? I can't wait for you answers!
Thank you very much!

**Comment by mesqueeb** [comment]
Hi @ctwhome 
It understand what you say. However, I don't think that creating modules (with different organizationIDs) dynamically is the best way to go.

You see with Vuex you'd usually want to have a single collection for all ideas so it's easy to link all kind of components to this single vuex module. Then that means there only has to be one instance of this module with all its methods and getters etc.

I think what's better in your situation is organazing the data of your multiple organizations in this one vuex module. So instead of `moduleName: 'organizations/{organizationId}/ideas'` I would more be looking for a functionality that keeps a single module like so:

```js
moduleName: 'ideas'
statePropName: 'data/{organizationId}'
```

Then it's much easier to link your components to whatever data is selected but still keep the same path for your actions, getters, etc. You could eg. add a state property to the module called `selectedOrganization` and then add a getter like so:
```js
getters: {
  shownIdeas (state) { return state.data[state. selectedOrganization] }
}
```
Makes sense? : D

That being said, this functionality (pathVariable in statePropName) doesn't exist yet currently...
I will have a little longer think about it and then decide if I will add it or not.

For the time being you can just open and close your database connection with different organizationIDs, and reset the model state in between.
The Firebase JS SDK which is used under the hood keeps data in cache anyway, so I'm sure this is for the time being just as good.

```js
dispatch('ideas/openDBChannel', {organizationId: 'a'})
dispatch('ideas/closeDBChannel', {clearModule: true})
dispatch('ideas/openDBChannel', {organizationId: 'b'})
```

**Comment by mesqueeb** [comment]
I have thought a bit more about this use case.

The reason I have not yet implemented `statePropName: 'data/{organizationId}'` is because every action you make would need to know against which organisation the changes need to be made. So I'm don't think this is a better approach after all. Also this would make the codebase much more complex.

I guess in this case it's better to have 1 module per organization after all (like you said), and instead support something like "dynamic module registration", as requested in #164 

I'm a bit worried about abuse though. When dynamically registering hundreds of modules, it could greatly impact the performance and am not sure if vuex was built for this.

**Comment by ctwhome** [comment]
Hi Luca! thanks for taking care of this.

this is how I am making it now thanks to you guidance:
```
 beforeRouteUpdate(to, from, next) {
    // just use `this`
    this.$store.dispatch('ideas/closeDBChannel', { clearModule: true })

    const organizationId = to.params.slug
    this.$store.dispatch('ideas/openDBChannel', { organizationId })
    next()
  },
```
It just works perfectly, as you said, firebase internals takes care of the caching and the ideas for an organization come back even after clearing the module even offline! wow man. That is awesome!
thank you very very very much for your support

**Comment by ctwhome** [comment]
in the other hand... it is very easy to filter ideas for an organization, they don't really have to live in sub-collections. If I want to filter ideas by user, having all the ideas in 1 module is the only way to have this without having to read all the organization. So another point to have just one module for all the ideas of the app, another module for all the comments.. etc.

Maybe it is interesting yet the idea of dynamic module registration, but I can't think right away of an useful example.

**Comment by mesqueeb** [comment]
No problem!!
I am happy i was able to help! I’ll close this thread and keep open #164 for now. But feel free to continue the discussion!

<sub><br>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
