### ISSUE TITLE
Guard for array props

### ISSUE THREAD

**Issue by halaprop** [mesqueeb/vuex-easy-firestore#175]
For props nested in an array prop, like:

`arrayProp: [ { allowed: true, notAllowed: true }, { allowed: true, notAllowed: true } ]`

I've noticed that specifying guard / sync for these, like this:

```
fillables: ['arrayProp.*.allowed']
guard: ['arrayProp.*.notAllowed']
```

Does not have the desired effect.  Am I mistaken in using it on an array?  If so, is there a work around?  (I've tried removing the locally added prop just before I save, but this causes my view's "react" in anger)

THANKS

**Comment by mesqueeb** [comment]
Hi @halaprop 
Indeed, guard is only usable for nested properties and it points to the property name.
Eg.
```js
dispatch('module/insert', {name: 'charlie', other: {data: {age: 1, color: 'red'}}})

// and in your module settings you have:
guard: ['other.data.color']

// then this will be inserted to the server instead:
dispatch('module/insert', {name: 'charlie', other: {data: {age: 1}}})
```
As you see above, the field called `color` was deleted before the data is pushed to the server.
Guard and nested are **arrays of "property names"**, but cannot look inside arrays.

In order to filter out specific elements in an array, you will need to use [hooks](https://mesqueeb.github.io/vuex-easy-firestore/hooks.html#hooks-on-local-changes).

In your case it would be something like this:
```js
  sync: {
    insertHook: function (updateStore, doc, store) {
      // find index of value inside an array
      const indexOfGuardValue = doc.someArray.indexOf('value-you-want-to-guard')
      if (indexOfGuardValue !== -1) {
         // modify array and remove the value
        doc.someArray.splice(indexOfGuardValue, 1)
      }
      updateStore(doc)
    },
    patchHook: function (updateStore, doc, store) { /* same as above */ },
  }
```

**Comment by halaprop** [comment]
Thanks.  I'm not aiming to remove values from an array.  I'm aiming to remove guarded key/values from objects contained in arrays. So I modified your suggestion to say this:

```
      // doc contains "arrayProp" and objects in arrayProp have guarded keys
      let guards = ['notAllowed1', 'notAllowed2']
      doc.arrayProp.forEach(objectInArray => {
        guards.forEach(guard => {
          if (objectInArray.hasOwnProperty(guard)) delete objectInArray[guard]
        })
      })
      console.log(doc)  // to debug
      updateStore(doc)
```
I can see on the console log that the objects inside arrayProp have the "notAllowed" keys removed.  Nevertheless, when I inspect the patched or inserted object on firebase console, the guarded keys reappear!

**Comment by mesqueeb** [comment]
@halaprop I see what you mean now.

First of all, deleting fields from an object is quite tricky because of how Firestore works.

Please read the firebase documentation on [deleting fields](https://firebase.google.com/docs/firestore/manage-data/delete-data) here.

### The reason why deleting is tricky

As you can see from the documentation, you need to use this: `firebase.firestore.FieldValue.delete()` to be able to delete a field.

Say in your store you have an object that looks like `{color: 'red', speed: 12}`.

```js
// not syncing `speed` won't cause the doc to delete `speed`:
firebase.firestore().doc('path/to/doc').update({color: 'red'})

// you have to do this instead:
firebase.firestore().doc('path/to/doc').update({speed: firebase.firestore.FieldValue.delete()})
```

### How this is integrated into Vuex Easy Firestore.

If we sync this special field right to Vuex, we'd have unexpected results, so we need to have special treatment for vuex-easy-firestore. That's why I have prepared a special `delete` action for this.

You can delete fields and nested fields by doing:
```js
dispatch('module/delete', 'field')
// or
dispatch('module/delete', 'field.nestedField')
```

### But what about arrays!!!

So working with arrays is tricky. Firebase actually recommends to [avoid arrays](https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html) as much as possible.

The reason is that, **every time you make a change to an object inside an array you need to re-sync the entire array**. You cannot change specific values on specific items in your arrays by design.

This is the reason why it's also not possible to have guarded props (in objects inside arrays) that will be prevented from being synced to Firebase but still are available in Vuex. 😅

I'm sorry, but I highly recommend you change to an object structure instead.

### What to do then?

I recommend you make your setup as follows:
```js
myObjectArray: {
  '1': { allowed: true, notAllowed: true }
  '2': { allowed: true, notAllowed: true }
}
```
This way you can still use `myObjectArray` like an array in `v-for` (because you can just pass objects as well), and you can use it "just like an array" with JavaScript very easily with the functions `Object.values` and `Object.keys` functions.

Finally, you can guard the props `notAllowed` by doing this:
```
sync: {
  guard: ['myObjectArray.*.notAllowed']
}
```

I hope this all makes sense?
If it solved your problem please close this issues!
Also feel free to continue the discussion. 😃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
@halaprop let me know how it went. I can give additional feedback and / or advice 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by halaprop** [comment]
Hi @mesqueeb - Thanks, and thanks for following up.  I investigated removing arrays from my data structure, and it will be too hard.  (There's an iOS app already in production that's rife with array dependencies).  Given that I must use arrays, and that I must add some guarded props to the objects they contain, and I can't think of a way to work around this restriction (e.g. deleting just before save, scrambles my views), I've decided to roll my own firestore adaptor.  I sure appreciate you making this package, and it helped me learn a lot.  Also appreciate how helpful you've been in these issue threads.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
