### ISSUE TITLE
[Bug] arrayRemove() + multiple items

### ISSUE THREAD

**Issue by danmalone89** [mesqueeb/vuex-easy-firestore#177]
Hello! I'm experiencing an weird issue while trying to remove multiple elements from an array field in a document. I have a document called a `feeGroup` and each document has a array field called `accounts` which is an array of firestore reference objects (i.e. `/accounts/123`). In my vue app, I have a method in which I want to use `removeArray()` to remove elements of the `accounts` field. 
Here's my method: 
```
    delete() {
      this.accounts.forEach(account => {
        if (account.feeGroup) {
          console.log(account); // successfully demonstrates loop.
          let feeGroupID = account.feeGroup.id;
          let accountRef = db.collection("accounts").doc(account.id);
          this.$store
            .dispatch("feeGroups/patch", {
              id: feeGroupID,
              accounts: arrayRemove(accountRef)
            })
            .then(id => console.log(`ID of document changed: ${id}`))
            .catch(e => console.error(e));
        }
      });
    }
```
When I execute this function however, only 1 element of the `accounts` array is being deleted, even though there are more that should.  See this console screenshot, as there is only 1 element reference in `updates`, although it clearly logged the **two** elements that should have been removed.
![image](https://user-images.githubusercontent.com/8354943/54320352-b5edb980-45ba-11e9-9d82-2d7414b2e0b0.png)

Any thoughts on what could be the issue here? I'm can't wrap my head around this. Thanks.

**Comment by mesqueeb** [comment]
Hello @danmalone89 
Thanks for your issue!
First of all this `length: 1` in the updates log shows the amount of documents an update was made to, not the amount of updates to a single document. So if you make 20 changes to 1 document and 1 change to another in the same collection, this will show `length: 2`. 🙃

Then, just to be clear, **what you want is to delete multiple same values in a single array?**

if Eg. this is your doc:
```js
{
  'doc-id-123': {
    id: 'doc-id-123',
    myArray: ['a', 'b', 'a']
  }
}
```
And you do this:
```js
dispatch('mymodule/set', {
    id: 'doc-id-123',
    myArray: arrayRemove('a')
})
```
You want to make sure that both `'a'` on index 0 and index 2 are removed, right?

If this is the case I'll add extra tests and make sure that `arrayRemove` removes ALL instances.

**Comment by danmalone89** [comment]
Thanks for the quick response. @mesqueeb! and the tips! That makes more sense. However, in your example, I'm actually trying to delete `a` and `b`.  Each item in my array is unique. Does that change how you would approach this? Thanks again!

**Comment by mesqueeb** [comment]
Ah, makes sense!!

You see what is happening is that currently i'm only supporting the deletion of a single item per call. I will need to rewrite it a bit to support multiple values in one call! 😅

BBut it doest't stop you from doing what you need. In your case, for the time being (until I update the library to support multiple values) you need to wait 1000 ms before making the second patch. Or you can force the first patch to be synced first and immidiately make the next one after. 

### No sync debounce on specific calls

You need to invoke the sync to ignore the debounce and have your patch immediately synced to the server.
For this you can just dispatch the following after your patch or insert action:
```js
dispatch('moduleName/patchc', yourArrayUpdate)
dispatch('moduleName/batchSync')
```
You'll have to do some testing on your end however. If this doesn't work (because the docs need to be prepared _before_ the batchSync, and I'm not sure that'll finish when immediately firing these two after each other) maybe you'll have to do this:
```js
dispatch('moduleName/insert', newDoc) // or patch or set
setTimeout(_ => dispatch('moduleName/batchSync'), 1)
```

### final note
If it your case you could also start with batchSync before any patch to the array, this case you always start fresh. 

Please let me know if the above solution I gave you work and if does close this issue!

<sub>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danmalone89** [comment]
Thanks @mesqueeb! Since these document updates don't need to happen _immediately,_ this is what I ended up with. Just in case anyone hits the same issue. 
```js
    delete() {
      this.accounts.forEach((account, index) => {
        setTimeout(() => {
          if (account.feeGroup) {
            let feeGroupID = account.feeGroup.id;
            let accountRef = db.collection("accounts").doc(account.id);
            this.$store
              .dispatch("feeGroups/patch", {
                id: feeGroupID,
                accounts: arrayRemove(accountRef)
              })
              .catch(console.error);
          }
        }, 2000 * (index + 1));
      });
    }

**Comment by mesqueeb** [comment]
@danmalone89 great! A delay of 1001 ms should work as well! 

By the way i'll keep this issue open until I make the possibility to delete multiple items simultaneously. 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Hi @danmalone89 
I fixed this issue in the latest version!
Please try `npm i vuex-easy-firestore@latest`

You can now use `arrayRemove(...arguments)` or `arrayRemove(value1, value2, value3)` etc.!

If it is fixed, please close the issue! ♡

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
