### ISSUE TITLE
How to assign custom userId from Google login

### ISSUE THREAD

**Issue by ctwhome** [mesqueeb/vuex-easy-firestore#195]
I am trying to set the userId with his email (i need to identify the users by the email, not by the uid from google) but I can\t find the way. in firestore the user is always written as the key of the connection "users" with the uid. 

``` moduleName: 'userData',
  statePropName: 'user',
  firestorePath: 'users/{userId}',   ==> I want to store here the email of the user as identifier.
  firestoreRefType: 'doc',
```
I assign the id into the user to save but nothing... this is the action that check when login
![image](https://user-images.githubusercontent.com/4195550/56694455-faef2a80-66e6-11e9-9c95-a9d25ed94517.png)

**Comment by mesqueeb** [comment]
@ctwhome You can do so with a custom variable instead of using `{userId}`.

Your module would look like
```js
SpecificGroupUserModule: {
  moduleName: 'customUserData',
  firestorePath: 'users/{customUserId}/data'
  // ...
}
```
and when you'd retrieve data do it like so:
```js
dispatch('groupUserData/openDBChannel', {customUserId: emailIdentifier})
```

Please see [detailed documentation here](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-filters).

Will this work in your case? Let me know! 😊

**Comment by ctwhome** [comment]
It is working now, Luca. Thank you very much!! and for the super fast response as always!
