### ISSUE TITLE
Uncaught (in promise) openDBChannel was already called for these filters and pathvariables.

### ISSUE THREAD

**Issue by preginald** [mesqueeb/vuex-easy-firestore#202]
I have the following console error messages everytime I change between 2 views.
```

> openDBChannel was already called for these filters and pathvariables. Identifier: [where][orderBy][pathVariables]{}
> Uncaught (in promise) openDBChannel was already called for these filters and pathvariables. Identifier: [where][orderBy][pathVariables]{}

```

In **AuthDash.vue** 
```
<script>
export default {
  data: () => ({
    contests: [{}]
  }),
  created() {
    this.$store.dispatch("contests/openDBChannel");
  }
};
</script>
```

In **Contests.vue** 

```
<script>
export default {
  data() {
    return {
      contest: { name: "", description: "" },
      events: [{ location: "", start: "" }]
    };
  },
  mounted() {
    this.$store.dispatch("events/openDBChannel");
  },
  methods: {
    loadEvent(id) {
      this.$router.push("/events/" + id);
    },
  }
};
</script>
```

**Comment by mesqueeb** [comment]
This is the expected behaviour.
My library will throw an error if you try to dispatch `openDBChannel` twice, unless if you change the pathVariables or where filters. 😉

The reason for this is that we want to **avoid multiple listeners on the same collection that do exactly the same thing**. Please read #71 for a more in depth discussion on this topic. 👀

In your case, you could avoid an error being thrown in the console by doing this:
```js
  mounted() {
    try {
      this.$store.dispatch("events/openDBChannel");
   } catch (e) {
     // Do nothing. Because the channel is already open.
   }
  },
```

Then IIRC the console log will show no more error. 🙃

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
