### ISSUE TITLE
Where should you call dispatch('myModule/openDBChannel')?

### ISSUE THREAD

**Issue by codegrue** [mesqueeb/vuex-easy-firestore#204]
If I have several pages that show the same collections or documents, do I try to call this once globally (e.g. in App.vue), or call it on every page independently (thus calling it many times during an application lifecycle?)

**Comment by mesqueeb** [comment]
Hi @codegrue 
Thanks so much for your support!!

Your question really depends on a lot of different factors so without looking at your code it's difficult for me to give you the best advice. 😁
You can always share your repository so I can have a look!!

## About multiple openDBChannels

Here's some advice about what happens when you call "openDBChannel" multiple times:

Every time you call `openDBChannel` it will create a [onSnapshot listener](https://firebase.google.com/docs/firestore/query-data/listen). Be sure to understand what that means by going through the Firebase docs.

It's possible to execute `onSnapshot` multiple times with exactly the same path / conditions, and what happens then is that when a document is added server side, **it will be synced to your client twice**. In order to prevent this useless battery drainage, I have made sure in vuex-easy-firestore that `openDBChannel` can only be called once with the same path / conditions. If it's already open and called again it will throw an error, like
> openDBChannel was already called for these filters and pathvariables. Identifier: _some info on your path/conditions_

You could catch this error and do nothing on just this error to prevent your JS thread from stopping execution. Maybe something like:
```js
try {
  dispatch('module/openDBChannel')
} catch (e) {
  if (e.includes('openDBChannel was already called')) {
    return // do nothing because this listener is already open
  }
  alert(`something went wrong. (${e})`)
}
```

I'm going to improve the way errors like these are returned in the future, but that will probably be after the summer when Vuex 3 came out and I'll bump this up a major version. So for now you can implement it like so and I'll make sure to not make any breaking changes.

## About the openDBChannel "path"

So what do I mean with _path_ above? That's simply the the firebasePath you are using.

If you have a [pathVariable](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-filters) set up and you change this variable then of course you can call `openDBChannel` again! However, to keep optimal performance, be sure to call `closeDBChannel` before doing so on the old path, because otherwise you'll have a bunch of listeners open for data you might not be showing to the user anymore.

## About the openDBChannel "coditions"

So what do I mean with _conditions_ above? That's simply the the [where filters](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#where-orderby-filters) you are using.

Same philosophy as the "path" above applies.

## When is calling openDBChannel multiple times useful?

Say you have a collection with to-do items and they have a single tag per item.
Each time you open a page and the router param ID is the TAG of the sub-set of items you want to load.

In this case you could do:
```js
created () {
  const tagId = this.$route.params.id
  if (!tagId) return
  this.$store.dispatch('myItems/openDBChannel', {where: [['tag', '==', tagId]]})
}
```
This created function each time loads the items with just the tag of the page the user opened.
(be sure to apply the `try-catch` I explained earlier.)

If the user will eg. go back and forth to different pages all loading items with different tags, you could opt to keep open your channels, but be sure to test for performance.

## When is calling openDBChannel a single time useful?

In our example above, you only load the relevant items when the user opens the page. However, if your users only have about 100~1000 items anyway, it might be better to just load ALL ITEMS when the user logs in right away. Then you can just show a different sub-set of your items through vuex-getters you set up. This will improve speed when the user opens a page, but reduce speed a bit on the initial load of all the items.

It's a tradeoff you'll have to think about which really depends on use case and your app. 😉

### Bonus tip
I'll give you an example of a vuex getter that works well with the vuex router param id, and doesn't require re-calculation when switching pages:

```js
export default {
  // your vef-module
  getters: {
    itemsPerTag (state) {
      return Object.values(state).reduce((carry, item) => {
        if (!carry[item.tag]) carry[item.tag] = []
        carry[item.tag].push(item)
        return carry
      }, {})
    }
  }
}
```

This getter only gets calculated once and then you can just show the relevant items based on the tag id when the user opens a page.
I'm showing you this because you gotta be careful if you create "**getters that return functions**" to eg. filter on an id. → they don't get cached!!

Thats' all! 😅

if there's anything else I can help with let me know!!

**Comment by codegrue** [comment]
Wow thanks for the detailed explanation. This helps a lot. Just to clarify one use case:

If I have a list page, and the user clicks on an item to go to a details page, should I do a new Id path based openDBChannel in the details page, or should I use a getter with an Id based filter on the original collection openDBChannel that the list page had?

**Comment by mesqueeb** [comment]
@codegrue Exactly!
It's really hard to say should I use this method or that method to retrieve docs? It's all about the best implementation for your use case, and what you feel most comfortable with yourself. 😉

What I often do if I'm not sure to implement something one way or the other, is I implement both methods and then choose the one that performs best / has the least code.
