### ISSUE TITLE
arrayUnion in dispatch(), prevent the same object.

### ISSUE THREAD

**Issue by Joey-Deakin** [mesqueeb/vuex-easy-firestore#207]
dispatch('events/patch', {
          id: this.event.id,
          times: arrayUnion({name: 'Jon Snow'})
        })

dispatch('events/patch', {
          id: this.event.id,
          times: arrayUnion({name: 'Jon Snow'})
        })

dispatch('events/patch', {
          id: this.event.id,
          times: arrayUnion({name: 'Jon Snow'})
        })

In the database, only one ({name: 'Jon Snow'})

**Comment by mesqueeb** [comment]
Hello @Joey-Deakin 

this is actually the expected behaviour. It is how ArrayUnion works in Firestore.
### From their [documentation](https://firebase.google.com/docs/firestore/manage-data/add-data):

> If your document contains an array field, you can use `arrayUnion()` and `arrayRemove()` to add and remove elements. `arrayUnion()` adds elements to an array but only elements not already present. `arrayRemove()` removes all instances of each given element.

Let me know if there's anything else! 🙃

PS:
 - please use this above code blocks → ```js
 - and this below code blocks → ```

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
