### ISSUE TITLE
vuex-module-decorators support ?

### ISSUE THREAD

**Issue by mtltechtemp** [mesqueeb/vuex-easy-firestore#209]
Hi,
There's not much to say, i'm struggling to make it work.
Can you add support for that? or steps in docs?
Thanks.

**Comment by mesqueeb** [comment]
Do you mean this?
[championswimmer/vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators)

In this case I won't be adding support for this, because in a few months VueJS 3 and the next Vuex versions will come out any way. They will have much better native support for typings.

I personally am avoiding any 3rd party typing solution because it'll probably become useless soon anyway.

Feel free to find someone to help you and make a PR though!!

I'm closing this for now, but feel free to keep the discussion going 😄
