### ISSUE TITLE
Timestamp conversion for manual fetch

### ISSUE THREAD

**Issue by theodore31** [mesqueeb/vuex-easy-firestore#215]
First off, I must say... **Amazing work!** I was hoping you can help me out with a particular issue I came across.

When performing a manual fetch, what is the proper syntax for converting timestamps to js dates?

My users module syncs "active" users, however I also perform a manual fetch for "inactive" users which is component specific.
```js
const getDefaultState = () => {
  return {
    activeUsers: {},
    inactiveUsers: {}
  }
}

const whereParam = [['active', '==', true]]
sync: {
    where: whereParam,
    orderBy: ['created_at', 'desc'],
    debounceTimerMs: 0
  },
serverChange: {
    convertTimestamps: {
      created_at: '%convertTimestamp%',
      updated_at: '%convertTimestamp%'
    }
}

// manual fetch
async getInactiveUsers ({ dispatch, commit }) {
    try {
      const querySnapshot = await dispatch('fetch', { where: [['active', '==', false]], limit: 200 })
      ...
}
```
The date fields returned from this query are:
```js
created_at: {
      nanoseconds:0
      seconds:1558843199
}
```
How can I handle this? (I hope I didn't miss this reading through the docs)

**Comment by mesqueeb** [comment]
Hi @theodore31 👋 
Thanks for the question.

There are a couple of ways you can do this.
If you dig in the source code, you'll come upon a Vuex Getter which is called `cleanUpRetrievedDoc`.
I'm using this getter to clean up any document coming from the server, also replacing the timestamps.

First you can have a look at the source code of `cleanUpRetrievedDoc` here:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/getters.ts#L89

# method 1
The first and **recommended way** would be to just use this getter like so:
```js
const querySnapshot = await dispatch('fetch', { where: [['active', '==', false]], limit: 200 })
querySnapshot.forEach(_doc => {
  const id = _doc.id
  const doc = getters.cleanUpRetrievedDoc(_doc.data(), id)
  // do something with your cleaned up doc! 🐯
})
```

In fact, this is exactly what `fetchAndAdd` does. It is just a wrapper around `fetch` and then cleans up the docs and adds them to vuex. 😉 
You can look at the source code of fetchAndAdd here:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/actions.ts#L354

# method 2

Otherwise you can google around a bit and you'll come to this Stack Overflow post:
> [How to get a JavaScript Date object from the new `firebase.firestore.FieldValue.serverTimestamp()`](https://stackoverflow.com/questions/51416027/how-to-get-a-javascript-date-object-from-the-new-firebase-firestore-fieldvalue/51416028)

A question asked and answered by yours truly. 🐥
If you have an SO account, feel free to vote up! XD

# PS
your post had horrible syntax highlighting. 😆 I edited and cleaned up your post. Can you see 
 the highlighting now? Edit it to see what I changed.

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by theodore31** [comment]
Method 1 is exactly what I needed! Super clean and simple ;) Thank you so much for the quick and detailed reply!

**Comment by mesqueeb** [comment]
@theodore31 please not that `cleanUpRetrievedDoc` also attaches any default values you may have set. 

See
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#default-values

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
