### ISSUE TITLE
Patch occasionally adds a nested object as a prop instead of updating only the nested element

### ISSUE THREAD

**Issue by colbyashcroft** [mesqueeb/vuex-easy-firestore#228]
We are having an issue where occasionally on a hard refresh of the application or on hot-reload the last patch that was done by vuex-easy-firestore will be re-run.  When it is re-run during the hard refresh it will make the update as a new prop rather than as an update to the individual field.

```
//example

//dummy document before any patch
id: 'abcdefg'
questions {
  12345678: {
     id: '12345678',
     order: 0,
     text: "this is a field i'm going to modify"
  },
  910111213: {
     id: '910111213',
     order: 1,
     text: "unmodified"
  }
}
// sample patch
dispatch('myCollection/patch', {id: 'abcdefg', questions: {12345678: {text: 'modified field'}}})

//dummy document after patch (everything is updated correctly)
id: 'abcdefg'
questions {
  12345678: {
     id: '12345678',
     order: 0,
     text: "modified field"
  },
  910111213: {
     id: '910111213',
     order: 1,
     text: "unmodified"
  }
}

//dummy document after app is refreshed (lowest level props have been removed)
id: 'abcdefg'
questions {
  12345678: {
     text: "modified field"
  },
  910111213: {
     id: '910111213',
     order: 1,
     text: "unmodified"
  }
}

//so for whatever reason it is removing all the additional fields at the lowest level while maintaining any other fields one level higher
```

**Comment by mesqueeb** [comment]
So this can have a couple of different reasons.

### Number prop-keys?
First of all, are you using numbers for prop-keys? I haven't tested yet with numbers as prop-keys, but because the firebase SDK requires to flatten patch data, this might cause issues.

With Firebase SDK, when you patch that field, the actual patch looks something like:
```js
firebase.firestore().doc('abcdefg').update({
  'questions.12345678.text': 'modified field'
})
```
My library takes care of this, but as you can see, there's no way of knowing if the sub-prop-key `12345678` is a number or a string.

I'm not sure if this is related but it's better to never use numbers as prop-keys (only use strings!!) in my opinion!

### Other problem?

If you try using only strings for prop-keys, and the problem still occurs, I'd have to take a closer look.

To find out the source, I would need to replicate your environment on my end, since the problem is not occurring on my end.

Just to be sure where the problem lies, can you look at the console.log of my library after the patch, tell me exactly what it logs after the patch action. (wether your fields were nested by my library or not)

And then after the first patch, how does it affect the data on Firestore? If you check the actual data on the Firebase console, does it still have all fields? If your DB has the correct data, it might be a cache problem...?

Please try some of these things and keep me informed!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by colbyashcroft** [comment]
Thanks for the prompt reply!

All of our props are strings, I apologize for the misleading example.  we are using the getters that you have defined to generate ID's for those nested object.
i.e. `getters['collection/dbRef'].doc().id;`
So I don't believe that is not the problem.  
Also, these are generally documents that have been update many times successfully and just under some weird string of events are not.


After the first patch both your console.logs and the cloud firestore are updated correctly.  
![image](https://user-images.githubusercontent.com/44585904/61490899-32c6e080-a96b-11e9-976e-ae2109b24c5d.png)
![image](https://user-images.githubusercontent.com/44585904/61491046-8c2f0f80-a96b-11e9-8ef0-a8ee6c5ef39a.png)


After a bad update you end up with a document that looks like this (we were patching a change of the prop order to a couple documents not text in this instance).
![image](https://user-images.githubusercontent.com/44585904/61491376-5e969600-a96c-11e9-8dc7-ae351a17a235.png)

Some of these patch errors that we believe are happening on hot reload are happening afterthe web app being idle for several minutes which leads us to believe the cache is the most likely culprit.

I'll work on creating a github repository with a minimized version of our application for you to test; but, right now the bug occurs pretty infrequently, (probably less than 5% of hot reloads), so we are trying to understand under which circumstances it actually occurs so we can reproduce it reliably.

**Comment by mesqueeb** [comment]
Ok. Thank you very much. I'd love to get to the bottom of this!

If your firestore still has the correct data, but it's _just_ your client that sometimes doesn't have all the data after reloading, we can do one more thing to check.

Try adding the `serverChange.addedHook` (see [docs](https://mesqueeb.github.io/vuex-easy-firestore/hooks.html#hooks-after-server-changes)).

This hook is fired _before_ my library actually adds the docs to the Vuex Store.
If you are able to add some conditional console.logging there, and you find that documents still have all fields when the addedHook is fired upon `openDBChannel`, but they are missing fields after they actually appear in the Vuex store, then I know **it's a problem with my library**.

If however, the fields are missing even during `addedHook`, then please try to manually add a Firebase Firestore onSnapshot listener like so: https://firebase.google.com/docs/firestore/query-data/listen

The onSnapshot listener is what my library uses under the hood. If the document is missing the fields even with the onSnapshot listener, that means that **the problem lies with the Firebase SDK**.

**Comment by mesqueeb** [comment]
Did it work? 🧐🥺🤗

**Comment by colbyashcroft** [comment]
After lots of troubleshooting we found the issue was something we were doing on our end.  Under a certain condition we would delete all the props in the object but when that happened it would update the UI; as we continued to modify the UI it would then rebuild the object slowly but some props would be missing because we were only updating single elements at a time. 

 Thank you so much for being so responsive and we sincerely apologize for wasting your time!  While troubleshooting the issue we did run into another issue that you said was previously fixed (https://github.com/mesqueeb/vuex-easy-firestore/issues/180)  We still see that issue though.

![firestore not deleting the prop](https://user-images.githubusercontent.com/44585904/62894583-364f4c80-bd0a-11e9-8b2a-dfb63465353c.gif)

As you can see in the GIF, when we delete a prop in one client,  it is not properly deleted in the other client when the server updates with the changes.  What I did not demonstrate in the GIF is if you refresh the client that still shows 4 props it will then match the client where the changes were made. 

I stripped down a version of our application and created a new firebase project where you can test this and see it yourself ( https://github.com/colbyashcroft/vuex_easy_firestore_troubleshooting) 
  1) clone repository
  2) npm install
  3) npm run serve
  4) navigate to "http://localhost:8080/masterDoc/5oH1595DhMNsf8CZV3we" in two separate windows (it needs a route to an actual document)
 5) Delete an element in window one (select and click backspace) and observe state in vue devtools in window 2 (changes will occure in in the vuex path -> masterDoc/masterDocData/userInputs


please let me know if you have any questions

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉

**Comment by louisameline** [comment]
Hi, I think this issue can safely be closed. I replied in the other issue.
