### ISSUE TITLE
[planned feature] Sync only if value has changed

### ISSUE THREAD

**Issue by Gnopps** [mesqueeb/vuex-easy-firestore#241]
To save on costs for syncing with Firestore an idea would be that the store is synced with Firestore only if the value has changed. As it is now `dispatch` will always overwrite the Firestore-value, even if the value is unchanged. The idea is to have an option that when enabled the dispatch first checks if new value is different from store value, and only then syncs with Firestore. 

To me this seems like an easy way to automatically save a lot on Firestore usage.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉

**Comment by louisameline** [comment]
This will need to be enabled by a global option or a per-dispatch parameter, because as always, you don't know for sure the actual value of the property at Firestore, unless you make a transaction, which doesn't make sense in this case as it would nullify the optimisation. So you could end up thinking you don't need to send the value to Firestore because it's already the same, while it's not. So this optimization should be used carefully, it might be ok or not depending on your use case. It should not be enabled by default.

**Comment by mesqueeb** [comment]
Very valid point. I'm gonna put it on the back burner for now. Open for counter arguments. 😄
