### ISSUE TITLE
is Date() for created_at or updated_at the best solution?

### ISSUE THREAD

**Issue by Fulbert** [mesqueeb/vuex-easy-firestore#245]
Hi !

First thanks for this awesome tools.

I'm a newbie, and not really familiar with date and time management in Javascript, or any other languages. Sorry if my question is dumb. ;)

I'm having trouble, as I want to use both moment and vuex-easy-firestore.
I get a Deprecation warning when I do someting like `{{ data.created_at | moment('from') }}`
If I understand correctly, the javascript Date object output might differ from one browser to another, which make it complicate to format. For this reason, in the next major version of moment, there'll be no fall back on Date to format (see http://momentjs.com/guides/#/warnings/js-date/).

I thought that I might just replace `created_at` and `updated_at` value with a firestore Timestamp object, but :

- I don't know if I can overwrite these properties (I saw I can use guards to avoid saving it, but what about replacing them ? I'll try.)
- I'll have to repeat the same hooks for all my stores to do that. Did I miss a solution to add hooks to all the stores ? (This could be a discussion in an another issue)

So I thought that it could be possible to add an option in vuex-easy-firestore to choose if we want to fill these properties with either Date or Timestamp. Would this be possible ? Am I missing something ?

Thanks,

**Comment by mesqueeb** [comment]
Hi @Fulbert thanks for your question!

While showing a `new Date()` instance with functions like `toLocaleString` might differ based on browser to browser, the information saved inside a `new Date()` instance does not.
(if it does, please tell me where you read this, because I'd find that extremely peculiar. 😅)

You can see here that the `Date` instance is supported in all browsers:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Browser_compatibility

Cloud Firestore interprets those Date instances that are being synced over, and it changes them to native Firestore "timestamps".

So nothing to worry concerning this!! 😄 

I'll close the issue for now, but if you do find a specific problem with `new Date()` and my library, please let me know!!

As for your questions:

- `I don't know if I can overwrite these properties (I saw I can use guards to avoid saving it, but what about replacing them ? I'll try.)`
  - You cannot overwrite them at this moment. However, you can add them to `guard` and just use a different field with your preferred method to store dates.
- `I'll have to repeat the same hooks for all my stores to do that. Did I miss a solution to add hooks to all the stores ? (This could be a discussion in an another issue)`
  - Hooks are module specific, so if you want to create a global hook you'll need to define the hook function in a separate file and import that in all modules you wish to use it. I'm doing this in some projects of mine as well. 😉 

PS: I would advice against using MomentJS, as it's a very big library often for things that can be solved with native JS Date class just as good. For more advanced cases try looking at smaller options like date-fns.

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by mesqueeb** [comment]
---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>
