### ISSUE TITLE
Offline persistence

### ISSUE THREAD

**Issue by tomasfil** [mesqueeb/vuex-easy-firestore#252]
Feature request, or question:

See if there are any local changes waiting to be synced into firebase.

**Comment by mesqueeb** [comment]
@tomasfil Hello!

Luckily offline persistence is already provided by the Firebase SDK ;)
Their documentation:
https://firebase.google.com/docs/firestore/manage-data/enable-offline

The **setup** documentation of Vuex Easy Firestore shows how you enable offline persistence:
https://mesqueeb.github.io/vuex-easy-firestore/setup.html#setup

When your app is opened offline, vuex-easy-firestore will just receive the docs from the Firestore cache instead of the server. It will work just the same as when it's online.
When changes are made, it will all be saved into the Firestore cache and the Firebase SDK will sync them when the device is back online.

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by mesqueeb** [comment]
---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>
