### ISSUE TITLE
question: OpenDBchannel only for currently fetchedandAdded documents

### ISSUE THREAD

**Issue by riksnelders** [mesqueeb/vuex-easy-firestore#254]
When calling openDBchannel it fetches everything.
I dont want to fetch all of it, I just want to realtime update on the fetchandAdd in that is synced to the vuex module.

Am I misunderstanding anything about how it works?

**Comment by mesqueeb** [comment]
Hi @riksnelders I think you might be misunderstanding something yes. 😅 

First of all, fetchAndAdd and openDBChannel are different they both execute a different function of the Firebase SDK:
-  openDBChannel executes "onSnapshot()" of the Firebase SDK
- fetchAndAdd executes "get()" of the Firebase SDK

I explained more on this in the [documentation](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#realtime-updates-vs-single-fetch). 😉

Also be sure to go over the the actual Firebase documentation on [onSnapshot](https://firebase.google.com/docs/firestore/query-data/listen) and [get](https://firebase.google.com/docs/firestore/query-data/get-data).

Then for your other question: "I dont want to fetch all of it"

It sounds to me like you want to filter what data is fetched or listened to. The Firestore SDK can do this via a `where()` function. My library also does this via where filters you can set. See the [documentation](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#where-orderby-filters) (and the Firebase [documentation](https://firebase.google.com/docs/firestore/query-data/queries#simple_queries) as well.)

Good luck! And feel free to open another issue if you run into problems ;)

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by riksnelders** [comment]
Thanks for the info @mesqueeb .

Adding a where I understand, but its not possible to limit the openDBchannel to 50 records and add records later if needed (realtime updates)

**Comment by mesqueeb** [comment]
@riksnelders No, because adding a "limit" to an "onSnapshot" listener in the Firebase SDK is also not possible 😉 

So it's kind of out of my control.

Basically my library is trying to make the Firebase SDK easier to use with a Vuex module, but features that are missing from the Firebase SDK are kind of out of my hands. 😛

Good luck! And feel free to open more issues.

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
