### ISSUE TITLE
Document getting recreated when deleting it

### ISSUE THREAD

**Issue by Nrevi** [mesqueeb/vuex-easy-firestore#258]
I have a cloud function that listens when a user is created and deleted - it creates a document for that user and deletes it. When I delete an account the document is getting deleted but instantaneously gets created back again. I’m pretty sure it has to do with offline persistence due to caching, is there a work around ?

**Comment by mesqueeb** [comment]
I have no idea. 😄  this is one of those cases I'd need to take a deep dive into the code 😅

**Comment by tomasfil** [comment]
First log off with that user account and then call closeDBChannel, just after that delete the user. Otherwise even if you delete the account from firebase, then the client is still "logged in". And when the channel is opened, then every period check it will create the document again. 

Try that and let us know.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉

**Comment by louisameline** [comment]
I spotted this issue too, although I haven't settled yet on the best way to solve it.
It happens in `openDBChannel` when the listener receives an empty response, it will "insert the initial document".
For the time being, you can turn the "insert the initial document" option to false, and do it yourself when you need to.

**Comment by louisameline** [comment]
So, after investigation, there are actually two things at hand here:
1. The document is recreated
1. The document is recreated with stale data in some cases, which comes from Firestore's cache at boot.

I won't bother you with the details of 2. , I don't even know if you actually met this bug, but it's been fixed in my PR which will be merged soon.

Now about the first issue, we'll keep recreating the document unless you set "insert the initial document" to false. It makes sense, because with this option you allow the user to write the document to Firebase if it doesn't exist, so why shouldn't he? Thanks

**Comment by mesqueeb** [comment]
@Nrevi Thanks to the incredible PR of @louisameline we were able to solve this issue!
Please let us know if you have any further trouble!! 🎉🎉🎉
