### ISSUE TITLE
Can't reference document in collection by id

### ISSUE THREAD

**Issue by findingorder** [mesqueeb/vuex-easy-firestore#288]
Hello,
I'm using realtime/collection mode, and creating a collection in my Vuex state as documented here: [https://mesqueeb.github.io/vuex-easy-firestore/add-and-manage-data.html#collection-mode](https://mesqueeb.github.io/vuex-easy-firestore/add-and-manage-data.html#collection-mode).

When I console.log the resulting state/data, it looks like this (with two documents in collection):
```js
{__ob__: Observer}
    1U7QJwazmhBjaI0C0HXB: (...)
    dm385N0nweo0JNnaMYPz: (...)
    __ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
    get 1U7QJwazmhBjaI0C0HXB: ƒ reactiveGetter()
    set 1U7QJwazmhBjaI0C0HXB: ƒ reactiveSetter(newVal)
    get dm385N0nweo0JNnaMYPz: ƒ reactiveGetter()
    set dm385N0nweo0JNnaMYPz: ƒ reactiveSetter(newVal)
    __proto__: Object
```

In my Vue component, in computed:, I want to use an id to obtain one of the objects from this collection.  So I do this: 
```js
computed: {
            ...mapState({
                fooData:  state => state.foo.data
            }),
            desiredFooDoc() {
                return this.fooData['dm385N0nweo0JNnaMYPz']
           }
//...
```
However it always returns undefined.  It appears that the fooData collection cannot be referenced using the id as a key.  In fact, if I call `Object.keys(this.fooData)` it returns an empty array `[]`.

So does anyone know how I can obtain one of the docs from this collection using the id as a key?

Thanks,
Phil

**Comment by mesqueeb** [comment]
Hi @findingorder 
This is probably a caveat of Vue rather than this library.

So what is probably happening is that when the computed property is created, it cannot attach a watcher onto the data you want, because it doesn't exist yet. Therefore the computed property will fail to be reactive, even when the property exists at a later date.

You have to work around it by using just `fooData['dm385N0nweo0JNnaMYPz']` in your template directly. That should work.

Let me know how it goes 😉 

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
