### ISSUE TITLE
Not fully specified path

### ISSUE THREAD

**Issue by tomasfil** [mesqueeb/vuex-easy-firestore#294]
Hello,

I am looking for a way to create where in which would be path something like
/userData/*AnyUser*/meetings
is that in any ways possible? I am trying to google it for some time, but without any help.

Thanks for any response.

**Comment by mesqueeb** [comment]
Hi @tomasfil 
I'm outside so I can't type a lot of explanation now, but it's all in the documentation here :

https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-clauses

Basically you should set it to `{anyUserId}` and then pass that variable any time you do openDBChannel or fetchAndAdd

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by louisameline** [comment]
Hi @tomasfil, I'm not sure but I think you are looking for collection query groups.
https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query

This is a bit of a tough subject, not currently handled by the library.
We plan better support for this feature in a future version of the library.

I'll close this issue due to the lack of activity and as I think it's the same as https://github.com/mesqueeb/vuex-easy-firestore/issues/248

Feel free to comment again if need be.
