### ISSUE TITLE
Allow dispatching an action with a Typescript model

### ISSUE THREAD

**Issue by beardo01** [mesqueeb/vuex-easy-firestore#298]
My use case is the following:

I have a component which creates a custom object (class defined in Typescript), dispatches a "set" action with this object and then in the `sync.insertHook`, converts the Typescript object to a plain old javascript object before inserting into Vuex. Currently, this causes the library to give a "Trying to merge a non-object... onto the defaultValues" error, so I have to move my conversion to before I dispatch the action.

Is this intended, and if so, can you see a use case for the situation that I've described?

Thanks in advance!

**Comment by mesqueeb** [comment]
Thanks for your issue. The thing is, the library needs to talk with this object and do all kind of things, copy it, attach I'd props, etc. As soon as I allow stuff other than plain objects, there's so many ways it could break. Eg. Copying a class instance is not the same as creating a new instance with the name Paramus etc.
So that's the main reason I'm reluctant to allow that. 

What's the reason that you want to do it in the hook rather than before dispatching the action ?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by beardo01** [comment]
Thanks for the prompt reply @mesqueeb. I guess it’s mainly to reduce complexity by having the conversion occur in one place (the hook) rather than in each of the many actions. Maybe requiring non native objects that are passed in to implement an interface is a happy middle ground?

At the end of the day if there is logical reasons to do it in the action versus the hook, then I can totally appreciate that and it isn’t a huge issue.

On a side note, I have an additional question about id’s. Should I open a seperate issue?

**Comment by mesqueeb** [comment]
Hi beardo.
It's in your case best to just write a simple wrapper action that handles your custom class instance and converts it to an object and then does the actual dispatch to 'insert' or 'patch'.
Such a wrapper action can even be defined in the same v-e-f module, so you would only need to define that once and have minimal refactoring I believe. 

This is the best solution is my opinion and I don't see any downsides. On the other hand , allowing v-e-f to accept custom class instances is a nightmare I don't want to get into. XD

Yes pls open a new issue for the other question! 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by beardo01** [comment]
Easy as. Thanks for your help!
