### ISSUE TITLE
Module naming and firestore structure

### ISSUE THREAD

**Issue by RobSteward** [mesqueeb/vuex-easy-firestore#314]
Hi,

I have the following firestore collection structure:
```
collection 1
collection 2
collection 3
settings (collection)
   -- global (doc)
      -- preserveState : true (prop)
      -- someOtherSetting : true
   -- map (doc)
      -- type: "map"
      -- maxFileSize: 2000000
```

my vuex module looks like this:
```
const settings = {
    firestorePath: 'settings',
    firestoreRefType: 'collection',
    moduleName: 'settings',
    statePropName: 'settings',
    namespaced: true,
}

export default settings
```

The "problem" here is that referencing this from my store now looks like this:
```
console.log(`This object is a ${{this.$store.state.settings.settings.mapSettings.type}}`)
```
This looks clumsy and inefficient.

Is there a better way to organize this?

**Comment by mesqueeb** [comment]
@RobSteward hey!
this really comes down to personal preferences, but what I always do is: whatever the module is (collection/doc) always use "data" as `statePropName`.
Then it would be `state.settings.data` instead of `state.settings.settings`.

BTW, organisation, naming and access be much improved in v2.0, which I'm working on hard now 😉

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
