### ISSUE TITLE
Insert promise not resolving in offline mode. Is this expected?

### ISSUE THREAD

**Issue by danmalone89** [mesqueeb/vuex-easy-firestore#344]
```
async saveDocument() {
 const id = await this.$store.dispatch('myModule/insert', doc)
 // document is added to Vuex store

 doSomethingWith(id) // unreachable while offline, despite document being successfully added to Vuex store.

}

```

Is this the expected behavior when offline? As soon as I go back online, the promise is resolved immediately. Firebase is constantly trying to write to server unsuccessfully while offline, throwing an error every second. I have offline persistence enabled.

**Comment by mesqueeb** [comment]
@danmalone89 
yes this is the expected behaviour.
The library immediately adds the document to the local state, so you don't really need to `await` that if that's good enough.

The `await` can be used to double check if the record is actually successfully written on the server side, which is therefore delayed when the client is offline.

In your case, you can either, retrieve the `id` from a hook like the [insertHook](https://mesqueeb.github.io/vuex-easy-firestore/hooks.html#hooks-on-local-changes), or you can create a random id yourself and pass it as prop to the doc you insert:
- `const randomId = firebase.firestore().collection('_').doc().id`

Let me know if you're stuck!

**Comment by danmalone89** [comment]
Thanks @mesqueeb!
