### ISSUE TITLE
Get Doc but id always equals null

### ISSUE THREAD

**Issue by adamelevate** [mesqueeb/vuex-easy-firestore#45]
When I call collections, the id comes back correctly for each item, but when calling a single document the id always is null... 

## store.js 
```javascript

const locksData = {
  firestorePath: 'locks/',
  firestoreRefType: 'collection', // collection or 'doc'
  moduleName: 'locksData',
  statePropName: 'data',
  sync:{
    where:[['cId', '==', '{customerId}']]
  }
}

const lockData = {
  firestorePath: 'locks/{lockId}/',
  firestoreRefType: 'doc', // collection or 'doc'
  moduleName: 'lockData',
  statePropName: 'data',
}
```
## component.js
```javascript
this.$store.dispatch('lockData/openDBChannel', {lockId: this.$route.params.lockId})
      .then(console.log)
      .catch(console.error)
```
### collection results
![image](https://user-images.githubusercontent.com/1000025/46075105-0fecf500-c1bc-11e8-9248-5c29c64de2dc.png)

## single doc result
![image](https://user-images.githubusercontent.com/1000025/46075003-c3091e80-c1bb-11e8-86cc-7449771cc1e4.png)

**Comment by mesqueeb** [comment]
@adamelevate Thanks for your post.
What do yoou mean **"when calling a single document"** do you use `dispatch('fetch')`?

**Comment by adamelevate** [comment]
Maybe I'm using this wrong, but I thought you needed to have a channel open for each collection or document you wanted to work with. 

For me, I have "locks" that need to be listed and a single "lock" I need to view/edit. So I have two channels, as shown in my "store.js" code above, and I'm trying to get a single document from the second channel called "lockData" in the "component.js" example above.

**Comment by mesqueeb** [comment]
@adamelevate You need to have the channel open to receive the data from the server yes.

However, the collection is enough.

In your case the `locksData` module is enough:
```js
  firestorePath: 'locks/',
  firestoreRefType: 'collection',
```
And you can completely remove the single `lockData` module.

So in your vuex store: `state.locksData.data` will receive all locks for the filter's you've set. And you can work with all those docs like so:

```js
eg.
const id = '' // get the id
dispatch('locksData', {id, active: false}) // to set active to false of a specific lock.
```

Is there a special reason that you need another module with a single lock?

**Comment by adamelevate** [comment]
No reason, maybe I don't understand the difference between collection and a docs mode. I guess it's silly to have to calls to firestore when I've already loaded the data once, the collection has every bit of data I could want. 

Either way, the doc mode still returns a null id, seems strange... right?

**Comment by mesqueeb** [comment]
Yes, I will make sure that the single doc in `'doc'` mode also fills in the id (which is the final part of the `firestorePath` in that case)

Thank you.

### About when to use 'collection' and when to use 'doc'

Use `firestoreRefType: 'doc'` if you want to just work with a single doc and not a collection of docs.

Eg. My users have a single "user settings" document saved per user. My module looks like:
```js
{
  firestorePath: 'users/{userId}/data/settings', // settings is a 'doc' inside the collection called "data"
  firestoreRefType: 'doc',
  moduleName: 'userSettings',
  statePropName: '', // save doc data directly to module state
}
```

Do you understand?

If there is something you need to do with a lock inside your locksData, and you can't find out how, pls ask me again!

**Comment by adamelevate** [comment]
Yeah, I understand your example. I think it's just getting used to the firestore ecosystem and normally I don't have the syntactic sugar this provides :)

**Comment by adamelevate** [comment]
Ok, yeah that makes sense... I'm still stuck in the architecture though. 

For example,
1. On the homepage I want to show all undelivered keys, 
2. When viewing a single lock, I want to show all keys for that lock. 

Am I opening two different channels or performing 2 fetch's? Does the "where" and "orderby" filters affect the fetch also? Sorry for nob questions, just don't understand how this library works with my use case... ty for your time!

**Comment by mesqueeb** [comment]
@adamelevate 

1. all undelivered keys
→　this should be a firestore collection and add the filters to get the undelivered ones.

2. when viewing a single lock, show all keys for that lock.
→　this will depend on how your database looks like. Can you give a little more info on that?

**Option A:**
You could eg. use `fetchAndAdd` or just `fetch` to get the keys for a single lock, if the user clicks on a lock.
Please go through the [documentation on fetch](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#fetching-docs-with-different-filters) again, I just updated it a little.

Some things to think about with this method:
- slightly slower loading time when opening a lock because the keys are only fetched then

**Option B:**
You could just retrieve all keys on beforehand via a firestore collection (and the same method as at 1. above). In this case you will get all keys in your vuex module, but only show the relevant ones to the user when he clicks on a lock.

This means that filtering the keys will happen in the front-end via JavaScript.
Some things to think about with this method:
- Keys will load faster when the user selects a lock, since they are already in your vuex module
- slightly longer initial loading time because you have to open the DBChannel
- not a good choice when there are eg. 1000s of keys (they all get retrieved and added to your vuex module), but a user would only look at a few dozen keys each session → option A might be better in this case.

**Comment by adamelevate** [comment]
Dude, you are going above and beyond to help me, I super appreciate it.

My database has locks, keys, and bunches of other stuffs. Each customer will have Thousands of locks and Thousands of keys, nature of the business.

There likely won't be many undelivered keys at any given point but there could be 50-100, I already have an index for that "delivered = false". That's where I'm opening my dbchannel, but once a user get's to a single lock page, I really need to make sure I have all the keys, "delivered true & false" for that single lock. 

My idea was to go with Option A, since I don't want to call thousands of keys that will never be seen. I need my db to be flat since many people at a customer will need to see the keys and subcollections aren't great for that, also have cloud functions that run to check for unused "key codes" to attach to keys after creation with other little helper functions.

## Lock page method "getKeys()"
```javascript
this.$store.dispatch('keysData/fetch', 
{whereFilters: [['lockId', '==', this.lockId],['cId', '==', this.user.cId]], orderBy: ['active_date']})
       .then(querySnapshot => {
         if (querySnapshot.done === true) {
           // console.log('querySnapshot',querySnapshot);
           vThis.isloadingKeys = false;
           vThis.loadKeys(querySnapshot);
           return 'all docs retrieved'
         }
       })
       .catch(console.error)
```
It worked once, asking me to make an index, which I did, then never worked again.

**Comment by mesqueeb** [comment]
@adamelevate Please try to read the [documentation on fetch](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#fetching-docs-with-different-filters) again.

**I had recently added `fetchAndAdd` opposed to just `fetch`.**

In your code snippet you are fetching, but not doing anything with the `querySnapshot`, that's why nothing happens. So I reckon you want to use `fetchAndAdd` instead!!

**Comment by mesqueeb** [comment]
@adamelevate any luck?

**Comment by mesqueeb** [comment]
I made sure that the single doc in 'doc' mode also fills in the id (which is the final part of the firestorePath in that case)
see #53
this closes this issue


@adamelevate feel free to keep on commenting if you are stuck with your fetch problem.
