### ISSUE TITLE
[Request] closeDBChannel function

### ISSUE THREAD

**Issue by svbeon** [mesqueeb/vuex-easy-firestore#58]
Hi,

In the example [Variables for firestorePath or filters](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-filters) there's an example that uses the user id to load data, one problem i have run into is that I want to load a specific collection's docs based on the store state, but i haven't found something like a `closeDBChannel` action which means that I end up syncing multiple DB locations to the same module's state. Is there any way i can `.off()` or is there something like `closeDBChannel` that I've missed?

Keep up the good work

**Comment by mesqueeb** [comment]
@svbeon I'm not 100% sure what you are trying to achieve. Can you give a step by step overview what you want to do?

I do feel however that you could use `fetch` if you need to retrieve a variable once. Please read the [documentation](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#fetching-docs-with-different-filters) and see if it's what you need.

With this you could basically just fetch one single doc and not open the DB Channel.
So make the vuex module with your firestore path a vuex-easy-firestore module, but just don't do `openDBChannel` and perform a single fetch.

Would that be what you want?

**Comment by svbeon** [comment]
Well that could maybe work as a workaround, but basically i have one DBChannel open say

```js
const subjectsModule = {
  firestorePath: 'subjects',
  firestoreRefType: 'collection',
  moduleName: 'subjects',
  statePropName: 'docs'
}
```

Then depending on which of those loaded documents is "selected" (aka i have a state for `selectedDoc` that holds a document id) i wan't to load another module:

```js
const testsModule = {
  firestorePath: 'subjects/{subject}/tests',
  firestoreRefType: 'collection', // or 'doc'
  moduleName: 'tests',
  statePropName: 'docs'
}
```

I don't want separate copies of testsModule for every doc loaded with subjectsModule (as i wan't to load as little data as possible from firebase, and only when i need it) so basically when i commit the new selected doc id to the state I'd like to unregister all listeners from testsModule, clear it's state and start it anew, basically

```js
mutations: {
  clearTests (state) {
      if (typeof state.tests === 'undefined') return
      state.tests.docs = {}
    }
},
actions: {
  loadNewTest (context, data) {
    // if (typeof this.getters !== 'undefined') this.getters['tests/dbRef'].off() // here i basically would like to close/remove/exit/kill the previusly nitialised testsModule
    this.commit('clearTests')
    this.dispatch('tests/openDBChannel', { subject: data.id })
  }
},
```

I still want the 2-way data sync to work for the loaded tests until i change the selected doc id/subject

(The optimal solution would of course be if i could load the documents in the subcollections directly as some other state/subcollection thing in the subjectsModule)

**Comment by mesqueeb** [comment]
@svbeon i’m gonna write some possible options for you here soon. In the mean time, do you really need tests to be in separate collections?

I believe if there is no permission issues but you just want to load the least data possible you could still achieve that with 1 collection but use different where filters etc. I believe this will greatly simplify your setup and solves many issues that will occur when you have separate collections. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@svbeon 
Based on your comments I have decided to do these two things:

### 1. closeDBChannel

First of all, I'll implement a `closeDBChannel` function this weekend, using this [firestore code](https://firebase.google.com/docs/firestore/query-data/listen#detach_a_listener).

### 2. dynamically create Vuex-easy-firestore modules

If your firestorePaths **need** to be seperated like so: `'subjects/{subject}/tests'` you will need to have 1 vuex-easy-firestore (hereinafter "v-e-f") module per possible route. (this is because v-e-f modules are only created with store instantiation) I will look into the possibilities to add a v-e-f module _dynamically_ based with the [vuex registerModule function](https://vuex.vuejs.org/guide/modules.html#dynamic-module-registration). In this case you can dynamically create and destroy modules based on user input.

However, this might take another week or two to implement.

What you should do:

- If you have a fixed amount of "subjects" with paths like `'subjects/{subject}/tests'` you should prepare all of those v-e-f modules and open/close the DBChannels dynamically (after I update that feature this weekend).
- If you don't have a fixed amount of "subjects" and you **need** your DB setup like that, you'll need to wait for my feature nr.2 above to be implemented.
- If you don't have a fixed amount of "subjects" **but you have no authentication/permission issues when you put all "tests" into the same "collection" then I would highly recommend that**. In this case you should open the DBChannel with a certain "where" filter for which "subject" is selected. Then when another is selected, you could just do an additional "fetchAndAdd" or close and open the DBChannel again **but with a different where filter**.

**Comment by jgiovanni** [comment]
+1 I was just about to ask about a `closeDBChannel` function! 🎉

**Comment by mesqueeb** [comment]
@svbeon @jgiovanni 
Here's a gif with `dispatch('closeDBChannel', {clearModule: true})`

![closedbchannel-clear](https://user-images.githubusercontent.com/3253920/46912030-86546a00-cfa6-11e8-8a12-ba8c7eec03a0.gif)

And if you add nothing it will keep all docs/items already synced in the module and also still sync every change, but just not listen for changes on the server side:

https://www.dropbox.com/s/ian3qypvqbuem0i/closeDBChannel.mov?dl=0

Do you guys have any opinion on the parameter name `clearModule` ? Is that obvious enough?

I'll push this build in a few hours and let you guys know.

**Comment by svbeon** [comment]
\o/ clearModule sounds good to me

**Comment by mesqueeb** [comment]
@svbeon 
Done!
Please see the [release notes](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.16.0).

As per my comment above, I'm not gonna implement this yet:
**2. dynamically create Vuex-easy-firestore modules**

Please let me know if you really need that and open another issue in that case. I'm happy to continue the discussion below about your app's architecture.

**Comment by jgiovanni** [comment]
Works great, thank you! This may seem a bit hacky but it works: by modifying the module's `_conf.firestorePath` before opening the channel again, I'm able to get the desired results. 
```js
store.dispatch("chats/messages/closeDBChannel", { clearModule: true })
store.state.chats.messages._conf.firestorePath 
// output => "chats/WprFVJWGR10Y6S4W9zv3/messages"
store.state.chats.messages._conf.firestorePath.replace(/\/([A-Za-z0-9]+)\//, `/${[NEW_ID]}/`)
// output => "chats/NEW_ID/messages"
store.dispatch("chats/messages/openDBChannel")
```

**Comment by svbeon** [comment]
Thanks! I'll try to test it out today or tomorrow. I actually moved to your suggested db model with less layers, this is just a small project so it doesn't clutter things too much. The reason I originally opted for the first model is that it becomes easier to mentally work with for me, as each subject owns a set of test, and never shares them with another subjects it just made sense to give them a parent/child relationship. But I can see a lot of usecases where a flatter model makes way more sense

**Comment by mesqueeb** [comment]
Hi everyone. I updated the library that it's easier to close and open with a new variable. 

This should now work out of the box:
```js
store.dispatch('projects/openDBChannel', { orgId: '123' })
store.dispatch('projects/closeDBChannel', { clearModule: true })
store.dispatch('projects/openDBChannel', { orgId: '456' })
```

To update `npm i vuex-easy-firestore@latest`

What changed under the hood :

`your_module._conf.firestorePath`  now keeps the variable placeholder  as is, and is only replaced with the variable in a new getter called `firestorePathComplete`

**Comment by mesqueeb** [comment]
Hi everyone in this thread!

I just wanted to comment on the topic of how to work with multiple sub-collections in Firestore (and this library).

In my opinion it is usually better to work with a flatter database and filter on certain fields (using `where()`).
Eg. when you have a collection of user [lists] with each a sub-collection with [items].
- You'll have a hard time querying items when searching through multiple lists;
- with this library you'll need to do `openDBChannel` and `closeDBChannel` and open again with new _pathVariables_ all the time.
- It will also be harder to implement functionality to allow an item to be added in multiple lists etc.

That's why in such a case it's usually better to have some basic "lists" info on a single document with maybe just the names of the lists. And have a single "items" collection which is not nested, with all items. Then query for items `.where('list', '==', 'something')`.

Thinking about the best database structure is **very important**. And I want to emphasize that if you need to use a lot of _pathVariables_ and also _open_ and _closeDBChannel_ a lot with vuex-easy-firestore, there is a big chance you do not have the best database structure.

I highly recommend everyone to watch these specific two videos on Firestore database structure by the Firebase team. They helped me a lot:

- [Maps, Arrays and Subcollections, Oh My! | Get to Know Cloud Firestore #4
](https://youtu.be/o7d5Zeic63s)
- [How to Structure Your Data | Get to Know Cloud Firestore #5](https://youtu.be/haMOUb3KVSo)

Keep the discussion going and good luck!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
