### ISSUE TITLE
Best way to reload documents with a different variable?

### ISSUE THREAD

**Issue by jameslave-dose** [mesqueeb/vuex-easy-firestore#65]
Say I have the following `vuex-easy-firestore` module, where a set of projects are located under a single organization:
```
const projectsModule = {
    firestorePath: 'organizations/{orgId}/projects',
    firestoreRefType: 'collection',
    moduleName: 'projects',
    statePropName: 'docs',
}
```
The module state can be populated from within a component with
```
this.$store.dispatch('projects/openDBChannel', { orgId: this.orgId })
```
So far so good. But when the user selects a different organization, I need the local projects state to be cleared and re-populated according to the new value of `orgId`. What's the most efficient `vuex-easy-firestore` way to do that? Thanks in advance!

**Comment by mesqueeb** [comment]
Dear James,
You can do something like:
```js
store.dispatch("chats/messages/closeDBChannel", { clearModule: true })
store.state.chats.messages._conf.firestorePath 
// output => "chats/WprFVJWGR10Y6S4W9zv3/messages"
store.state.chats.messages._conf.firestorePath.replace(/\/([A-Za-z0-9]+)\//, `/${[NEW_ID]}/`)
// output => "chats/NEW_ID/messages"
store.dispatch("chats/messages/openDBChannel")
```
(credit to @jgiovanni and his [post](https://github.com/mesqueeb/vuex-easy-firestore/issues/58#issuecomment-429621148))

It should work fine. Just adjust a little to your config.

I will think about better ways to do this in the future and let you know here if I come up with any new ideas or if I add a new functionality to the library.

Feel free to continue the conversation and let me know if you're stuck. If you get it working please close the issue. Thakns!

**Comment by berendsmatt** [comment]
Hi Luca,

I thought it was going to work this way...
`store.dispatch("projects/closeDBChannel", { clearModule: true })
this.$store.dispatch('projects/openDBChannel', { orgId: <newOrgId> })
`
Can the call openDBChannel set a NEW_ID if one is passed?
`store.state.chats.messages._conf.firestorePath.replace(/\/([A-Za-z0-9]+)\//, `/${[NEW_ID]}/`)`

**Comment by mesqueeb** [comment]
>Hi Luca, ...

@berendsmatt you currently cannot pass a new path-variable (id) just like that because on the first openDBChannel the firestore path gets replaced with the path with the variables filled in. 
Therefor on the second time it will not know where to place your new path-variable. 

I will need to improve this and will do so this weekend.

Until then please manually do a replace of your old path variable with the new one in `your_module._conf.firestorePath` and also pass it again on openDBChannel to be sure where filters that use that variable won’t break. 

Sorry if it’s a bit confusing right now. : S


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Hi everyone. I updated the library that it's easier to close and open with a new variable. 

This should now work out of the box:
```js
store.dispatch('projects/openDBChannel', { orgId: '123' })
store.dispatch('projects/closeDBChannel', { clearModule: true })
store.dispatch('projects/openDBChannel', { orgId: '456' })
```

To update `npm i vuex-easy-firestore@latest`

What changed under the hood :

`your_module._conf.firestorePath`  now keeps the variable placeholder  as is, and is only replaced with the variable in a new getter called `firestorePathComplete`

**Comment by berendsmatt** [comment]
Been waiting for this update.
Thanks mate.

**Comment by mesqueeb** [comment]
Let me know if any troubles arise! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coolhand79** [comment]
I created an issue, but I'm not quite sure how to turn it into a bug....

BTW - you're _crushing_ it! You've got something here, I really like it!

**Comment by mesqueeb** [comment]
Much appreciated!! I try to help people wherever I can. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Hi everyone in this thread!

I just wanted to comment on the topic of how to work with multiple sub-collections in Firestore (and this library).

In my opinion it is usually better to work with a flatter database and filter on certain fields (using `where()`).
Eg. when you have a collection of user [lists] with each a sub-collection with [items].
- You'll have a hard time querying items when searching through multiple lists;
- with this library you'll need to do `openDBChannel` and `closeDBChannel` and open again with new _pathVariables_ all the time.
- It will also be harder to implement functionality to allow an item to be added in multiple lists etc.

That's why in such a case it's usually better to have some basic "lists" info on a single document with maybe just the names of the lists. And have a single "items" collection which is not nested, with all items. Then query for items `.where('list', '==', 'something')`.

Thinking about the best database structure is **very important**. And I want to emphasize that if you need to use a lot of _pathVariables_ and also _open_ and _closeDBChannel_ a lot with vuex-easy-firestore, there is a big chance you do not have the best database structure.

I highly recommend everyone to watch these specific two videos on Firestore database structure by the Firebase team. They helped me a lot:

- [Maps, Arrays and Subcollections, Oh My! | Get to Know Cloud Firestore #4
](https://youtu.be/o7d5Zeic63s)
- [How to Structure Your Data | Get to Know Cloud Firestore #5](https://youtu.be/haMOUb3KVSo)

Keep the discussion going and good luck!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
